markdown: kramdown
highlighter: rouge

collections:
  # gui:
  #   output: true
  projects:
    output: true
    permalink: /projects/:path/
  

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "project"